services:
    database:
        container_name: database
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
            POSTGRES_DB: discord
        ports:
            - 5432:5432

    adminer:
        container_name: adminer
        image: adminer
        restart: always
        ports:
            - 8080:8080
